import { Inter_Tight } from "next/font/google";
import "./globals.css";

const inter = Inter_Tight({
  weight: "600",
  subsets: ["latin"],
});

export const metadata = {
  title: "ReqJet (API Tester)",
  description: "Generated by create next app",
};

import MainNav from "@/components/main-nav/main-nav";
import { LeftSideBar } from "@/components/main-nav/sidebar";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-slate-500`}>
        <MainNav />
        <div className="flex flex-shrink h-[calc(100vh-49px)] w-full">
          <LeftSideBar className="flex-none" />
          {children}
        </div>
      </body>
    </html>
  );
}
